# Generated by Django 5.0.14 on 2025-07-16 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(db_column='CommentID', primary_key=True, serialize=False)),
                ('trail_id', models.IntegerField(db_column='TrailID')),
                ('comment_text', models.TextField(db_column='CommentText')),
                ('datetime_posted', models.DateTimeField(db_column='DatetimePosted', default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(db_column='IsEdited', default=False)),
                ('last_edit_datetime', models.DateTimeField(blank=True, db_column='LastEditDateTime', null=True)),
                ('is_archived', models.BooleanField(db_column='IsArchived', default=False)),
                ('archived_by', models.ForeignKey(blank=True, db_column='ArchivedByID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_comments', to='comments.user')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='comments.user')),
            ],
            options={
                'db_table': 'Comment',
                'ordering': ['-datetime_posted'],
            },
        ),
    ]
