# Generated by Django 5.0.14 on 2025-08-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='CW2.Comment',
        ),
        migrations.AlterModelTable(
            name='reply',
            table='CW2.Reply',
        ),
        migrations.AlterModelTable(
            name='user',
            table='CW2.User',
        ),
    ]
